src/views/auth.py
import functools
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash
from src.data.db import get_db

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        user_name = request.form ['user-name']
        user_id = request.form ['user-id']
        user_birthday = request.form ['user-birthday']
        user_phone = request.form ['user-phone-number']
        user_email = request.form ['user-email']
        user_password = request.form ['user-password']
        db = get_db()
        error = None

        if error is None:
            try:
                db.execute(
                    "INSERT INTO seller (id, name, birthday, phone_number, email, password) VALUES (?, ?, ?, ?, ?, ?)",
                    (user_id, user_name, user_birthday, user_phone, user_email, generate_password_hash(user_password)),
                )
                db.commit()
            except db.IntegrityError:
                error = f"Usuário já cadastrado"
            else:
                return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        user_id = request.form ['user-id']
        user_password = request.form ['user-password']
        db = get_db()
        error = None
        user = db.execute(
            'SELECT * FROM seller WHERE id = ?', (user_id,)
        ).fetchone()

        if user is None:
            error = 'Usuário ou senha incorreta.'
        elif not check_password_hash(user['password'], user_password):
            error = 'Usuário ou senha incorreta.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            session['user_name'] = user['name']
            return redirect(url_for('dashboard.welcome'))

        flash(error)
        
    return render_template('auth/login.html')

@bp.route('/logout')
def logout():
        session.clear()
        return redirect(url_for('home'))

src/views/cash_register.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)

from src.data.db import get_db
from src.views.sale import get_last_sale

bp = Blueprint('cash_register', __name__, url_prefix='/cash_register')

@bp.route('/open', methods=('GET', 'POST'))
def open():
    db = get_db()

    if request.method == "POST":
        seller_id = session['user_id']
        status = "Aberto"
        cash_fund = request.form['cash-fund']
        error = None

        if error is None:
            try:
                db.execute(
                    "INSERT INTO cash_register (seller_id, status, cash_fund) VALUES (?, ?, ?)",
                    (seller_id, status, cash_fund),
                )
                db.commit()
            except db.IntegrityError:
                error = f"Caixa já aberto"
            else:
                return redirect(url_for('dashboard.welcome'))

    try:
        cash = db.execute(
            'SELECT * FROM cash_register WHERE id = (SELECT MAX(id) FROM cash_register)'
        ).fetchone()

        if cash['status'] == 'Fechado':
            return render_template('pos/open.html')
        else:
            return redirect(url_for('dashboard.welcome'))
    except TypeError:
        return render_template('pos/open.html')
    

@bp.route('/close', methods=('GET', 'POST'))
def close():
    db = get_db()
    
    if request.method == "POST":
        status = "Fechado"
        revenue_declared = request.form['revenue']
        expenses_declared = request.form['expenses']
        error = None

        if error is None:
            try:
                db.execute(
                    "UPDATE cash_register SET status = ?, revenue_declared = ?, expenses_declared = ? WHERE id = (SELECT MAX(id) FROM cash_register)",
                    (status, revenue_declared, expenses_declared),
                )
                db.commit()
            except db.IntegrityError:
                error = f"Caixa já fechado"
            else:
                return redirect(url_for('dashboard.welcome'))

    try:
        cash = db.execute(
            'SELECT * FROM cash_register WHERE id = (SELECT MAX(id) FROM cash_register)'
        ).fetchone()

        if cash['status'] == 'Aberto':
            return render_template('pos/close.html', cash=cash)
        else:
            return redirect(url_for('dashboard.welcome'))
    except TypeError:
        return render_template('pos/close.html', cash=cash)

@bp.route('/update')
def update():
    sale = get_last_sale()
    db = get_db()
    db.execute(
        'UPDATE cash_register SET revenue = (revenue + ?), sales_number = sales_number + 1, products_sold = (products_sold + ?) WHERE id = (SELECT MAX(id) FROM cash_register)',
        (sale['sale_total_price'], sale['itens_quantity'])
    )
    db.commit()
    
    return redirect(url_for('dashboard.welcome'))

src/views/dashboard.py
import functools
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from datetime import datetime
from src.data.db import get_db
from src.views import auth

bp = Blueprint('dashboard', __name__, url_prefix='/dashboard')

@bp.route('/', methods=('GET', 'POST'))
def welcome():
    if 'user_id' in session:
        now = datetime.now()
        date_time = now.strftime("%d/%m/%Y")

        db = get_db()

        current_cash = db.execute(
            'SELECT * FROM cash_register WHERE id = (SELECT MAX(id) FROM cash_register)'
        ).fetchone()

        daily_cash = db.execute(
            'SELECT SUM(revenue), SUM(sales_number), SUM(products_sold) FROM cash_register WHERE DATE(cash_date) = CURRENT_DATE'
        ).fetchone()
        
        return render_template('pos/dashboard.html', date_time=date_time, current_cash=current_cash, daily_cash=daily_cash)

    return redirect(url_for('auth.login'))

src/views/sale.py
from datetime import datetime
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)

from src.data.db import get_db

bp = Blueprint('sale', __name__, url_prefix='/sale')

def get_last_sale():
    db = get_db()
    sale = db.execute(
            'SELECT * FROM sale WHERE id = (SELECT MAX(id) FROM sale)'
        ).fetchone()

    return sale

    
def get_item(id):
    db = get_db()
    item = db.execute(
        'SELECT * FROM sale_item WHERE id = ?', (id,)
    ).fetchone()

    return item

def get_product(id):
    db = get_db()
    product = db.execute(
        'SELECT * FROM product WHERE id = ?', (id,)
    ).fetchone()

    return product


@bp.route('/new')
def new_sale():

    db = get_db()

    current_cash = db.execute(
        'SELECT * FROM cash_register WHERE id = (SELECT MAX(id) FROM cash_register)'
    ).fetchone()

    status = current_cash['status']
    seller = session['user_id']

    if status == 'Aberto':
        db.execute(
            'INSERT INTO sale (seller_id, cash_register_id) VALUES(?, ?)', (seller, current_cash['id'])
        )
        db.commit()

        last_sale = get_last_sale()
        id = last_sale['id']

        return redirect(url_for('sale.checkout', id = id))
    else:
        return redirect(url_for('dashboard.welcome'))


@bp.route('/<int:id>/', methods=('GET', 'POST'))
def checkout(id):

    now = datetime.now()
    date_time = now.strftime("%d/%m/%Y")
    sale = get_last_sale()

    if request.method == 'POST' and 'submit-add' in request.form:
        product_id = request.form['product-id']

        product = get_product(product_id)

        db = get_db()
        db.execute(
            'INSERT INTO sale_item (product_id, product_price, quantity, subtotal, sale_id) VALUES (?, ?, ?, ?, ?)',
            (product['id'], product['price'], '1', product['price'] , id)
        )
        db.commit()
        
        return redirect(url_for('sale.update_sale', id = id))
    

    if request.method == 'POST' and 'submit-checkout' in request.form:
        payment_method = request.form['payment-method']
        costumer = request.form['costumer']

        db = get_db()
        db.execute(
            'UPDATE sale SET payment_method = ?, status = ? WHERE id = ?', (payment_method, 'Concluída', id)
        )
        db.commit()

        if costumer != '':
            db.execute(
            'UPDATE sale SET costumer_id = ? WHERE id = ?', (costumer, id)
        )
        db.commit()

        return redirect(url_for('cash_register.update'))

    db = get_db()
    sale_itens = db.execute(
        'SELECT p.name, p.author, si.id, si.product_id, p.price, si.quantity, si.subtotal FROM sale_item si JOIN product p ON p.id = si.product_id WHERE si.sale_id = ? ORDER BY si.id DESC', (id,)
    ).fetchall()


    return render_template('pos/sale.html', sale_itens = sale_itens, sale = sale, date_time = date_time)


@bp.route('/<int:id>/update')
def update_sale(id):
    db = get_db()

    try:
        sale = db.execute(
            'SELECT SUM(quantity) AS quantity, SUM(subtotal) AS total FROM sale_item JOIN sale ON sale_item.sale_id = sale.id WHERE sale_id = (SELECT max(id) from sale)'
        ).fetchone()

        db.execute(
            'UPDATE sale SET itens_quantity = ?, sale_total_price = ? WHERE id = ?', (sale['quantity'], sale['total'], id)
        )
        db.commit()

    except db.IntegrityError:
        db.execute(
            'UPDATE sale SET itens_quantity = 0, sale_total_price = 0 WHERE id = ?', (id,)
        )
        db.commit()

    return redirect(url_for('sale.checkout', id = id))

@bp.route('/<int:id>/cancel')
def cancel_sale(id):
    db = get_db()

    db.execute(
        'DELETE FROM sale WHERE id = ?', (id,)
    )
    db.commit()

    return redirect(url_for('dashboard.welcome'))


@bp.route('/<int:id>/plus')
def plus_item(id):
    get_item(id)

    db = get_db()
    db.execute(
        'UPDATE sale_item SET quantity = quantity +1 WHERE id = ?', (id,)
        )
    db.commit()

    db.execute(
        'UPDATE sale_item SET subtotal = product_price * quantity WHERE id = ?', (id,)
        )
    db.commit()

    last_sale = get_last_sale()
    id = last_sale['id']

    return redirect(url_for('sale.update_sale', id = id))


@bp.route('/<int:id>/minus')
def minus_item(id):
    get_item(id)

    db = get_db()
    db.execute(
        'UPDATE sale_item SET quantity = quantity -1 WHERE id = ?', (id,)
        )
    db.commit()

    db.execute(
        'UPDATE sale_item SET subtotal = product_price * quantity WHERE id = ?', (id,)
        )
    db.commit()

    last_sale = get_last_sale()
    id = last_sale['id']

    return redirect(url_for('sale.update_sale', id = id))


@bp.route('/<int:id>/delete')
def delete_item(id):
    get_item(id)

    db = get_db()
    db.execute(
        'DELETE FROM sale_item WHERE id = ?', (id,)
        )
    db.commit()

    last_sale = get_last_sale()
    id = last_sale['id']

    return redirect(url_for('sale.update_sale', id = id))

src/templates/pos/close.html
{% extends 'base.html' %}
{% block title %}Nova venda{% endblock %}
{% block content %}
<div class="cash-register-container column flex">
    <div class="title">
        <h1>Fechamento de caixa</h1>
    </div>

    <form action="" method="POST" id="open-cash-register" class="flex column">
        <div class="flex column">
            <label for="cash-fund">Entradas: R${{cash['revenue']}}</label>
            <input type="text" name="revenue" id="revenue">
        </div>

        <div class="flex column">
            <label for="cash-fund">Saídas: R${{cash['expenses']}}</label>
            <input type="text" name="expenses" id="expenses">
        </div>

        <button type="submit">Fechar caixa</button>
    </form>

</div>
{% endblock %}

src/templates/pos/dashboard.html
{% extends 'base.html' %}
{% block title %}Seja bem-vindo{% endblock %}
{% block content %}
<div class="dashboard-container dash-radius">
    <div class="dashboard-col-left flex-2 flex column dash-radius">
        <div class="row row1 flex dash-radius box-shadow">
            <div id="user-greeting"> Olá, {{session['user_name']}}!</div>
            <div id="logout">
                <a href=" {{ url_for('auth.logout') }} ">Logout</a>
            </div>
        </div>

        <div class="row row2 flex dash-radius">
            <div class="row-col flex column dash-radius box-shadow" id="abrir-caixa">
                <span class="material-symbols-outlined m-48">
                    point_of_sale
                    </span>
                <div>Abrir caixa</div>
                <a href=" {{ url_for('cash_register.open') }} " class="card-link"></a>
            </div>
            <div class="row-col flex column dash-radius box-shadow" id="nova-venda">
                <span class="material-symbols-outlined m-48">
                    add_shopping_cart
                    </span>
                <div>Nova venda</div>
                <a href=" {{ url_for('sale.new_sale') }} " class="card-link"></a>
            </div>
            <div class="row-col flex column dash-radius box-shadow" id="fechar-caixa">
                <span class="material-symbols-outlined m-48">
                    enterprise_off
                    </span>
                <div>Fechar caixa</div>
                <a href=" {{ url_for('cash_register.close') }} " class="card-link"></a>
            </div>
        </div>

        <div class="row row3 flex dash-radius box-shadow">
            <div class="dashboard-search flex column">
                <div class="flex ">
                    <span class="material-symbols-outlined" style="margin-right: 10px">
                        quick_reference_all
                    </span>
                    <div>Buscar produto</div>
                </div>

                <form method="POST" name="product-search">
                    <input type="text" class="dashboard-search-input">
                    <button type="submit" class="search-button">Buscar</button>
                </form>

            </div>
        </div>
            
        <div class="row row4 flex dash-radius box-shadow">
            <div class="dashboard-search flex column">
                <div class="flex">
                    <span class="material-symbols-outlined" style="margin-right: 10px">
                        person_search
                    </span>
                    <div>Buscar cliente</div>
                </div>

                <form method="POST" name="client-search">
                    <input type="text" class="dashboard-search-input">
                    <button type="submit" class="search-button">Buscar</button>
                </form>
            </div>
        </div>
    </div>
    <div class="dashboard-col-right flex-1 flex column dash-radius">
            <div class="row row5 flex column dash-radius box-shadow">
                <div class="dashboard-stats date">{{ date_time }}</div>

                <div class="flex dashboard-stats">
                    <span class="material-symbols-outlined m-36">
                        store
                    </span>

                    <div class="flex column">
                        <div name="sales-number"> {{ current_cash['status'] }} </div>
                        <label for="sales-number">Status do caixa</label>
                    </div>  
                </div>

                <div class="flex dashboard-stats">
                    <span class="material-symbols-outlined m-36">
                        receipt_long
                    </span>

                    <div class="flex column">
                        <div name="sales-number">{{ daily_cash['SUM(sales_number)'] }}</div>
                        <label for="sales-number">Vendas</label>
                    </div>  
                </div>
                
                <div class="flex dashboard-stats">
                    <span class="material-symbols-outlined m-36">
                        sell
                    </span>

                    <div class="flex column">
                        <div name="products-sold">{{ daily_cash['SUM(products_sold)'] }}</div>
                        <label for="products-sold">Produtos vendidos</label>
                    </div>

                </div>

                <div class="flex dashboard-stats">
                    <span class="material-symbols-outlined m-36">
                        payments
                    </span>

                    <div>
                        <div name="total-income">R$ {{ daily_cash['SUM(revenue)'] }}</div>
                        <label for="total-income">Faturamento</label>
                    </div>
                </div>  
            </div>
            <div class="row row6 dash-radius flex column box-shadow">
                <div class="flex column dashboard-history" id="history">
                    <span class="material-symbols-outlined m-48">
                        bar_chart
                    </span>

                    <div>Histórico</div>
                </div>
            </div>
    </div>
</div>

{% endblock %}

src/templates/pos/open.html
{% extends 'base.html' %}
{% block title %}Nova venda{% endblock %}
{% block content %}
<div class="cash-register-container column flex">
    <div class="title">
        <h1>Abertura de caixa</h1>
    </div>

    <form action="" method="POST" id="open-cash-register" class="flex column">
        <label for="cash-fund">Fundo de caixa</label>
        <input type="text" name="cash-fund" id="cash-fund">
        <button type="submit">Abrir caixa</button>
    </form>

</div>
{% endblock %}

src/templates/pos/sale.html
{% extends 'base.html' %}
{% block title %}Nova venda{% endblock %}
{% block content %}

    <div class="sales-container flex column">
        <div class="sale-header flex">
            <div class="flex" style="gap: 15px; align-items: center;">
                <div>Venda #{{sale['id']}}</div>
                <form>
                    <button formaction=" {{ url_for('sale.cancel_sale', id = sale['id']) }} " class="cancel-sale-button">Cancelar</button>
                </form>   
            </div>
            <div>Vendedor: {{session['user_name']}}</div>
        </div>

        <div class="sale-search flex column">
            <div class="flex ">
                <span class="material-symbols-outlined" style="margin-right: 10px">
                    library_add
                </span>
                <div>Adicionar produto</div>
            </div>

            <form action="" method="POST" name="product-add" id="product-add">
                <input type="text" class="sale-add-input" name="product-id" required>
                <button type="submit" class="add-button" name="submit-add">Adicionar</button>
            </form>

        </div>

        <div class="sale-list flex column border">

            {% for item in sale_itens %}

                <div class="sale-itens flex">
                    <div class="item-info flex" style="flex: 8">
                        <div class="item-name" style="flex: 6">{{item['name']}}</div>
                        <div class="item-author" style="flex: 3">{{item['author']}}</div>
                        <div class="item-price" style="flex: 1">R$ {{item['subtotal']}}</div>
                    </div>
                    

                    <div class="item-quantity flex" style="flex: 1.5">
                        <div class="alter-quantity">
                            <span class="material-symbols-outlined m-16">
                                remove
                            </span>
                            <a href="{{ url_for('sale.minus_item', id = item['id']) }}" class="sale-icon"></a>
                        </div>
                        
                        <div>{{item['quantity']}}</div>

                        <div class="alter-quantity">
                            <span class="material-symbols-outlined m-16">
                                add
                            </span>
                            <a href="{{ url_for('sale.plus_item', id = item['id']) }}" class="sale-icon"></a>
                        </div>
                    </div>

                    <div class="item-delete flex" style="flex: 0.5">
                        <span class="material-symbols-outlined m-16">
                            delete
                        </span>
                        <a href="{{ url_for('sale.delete_item', id = item['id']) }}" class="sale-icon"></a>
                    </div>
                    
                </div>

            {% endfor %}

        </div>

        <div class="bottom-container flex">
            <div class="summary flex column">
                <div class="summary-title"">Resumo</div>
                <div class="sale-date flex">
                    <div>Data</div>
                    <div>{{ date_time }}</div>
                </div>

                <div class="quantity flex">
                    <div>Itens</div>
                    <div>{{ sale['itens_quantity']}}</div>
                </div>

                <div class="total flex">
                    <div>Total</div>
                    <div>R$ {{ sale['sale_total_price']}}</div>
                </div>
            </div>

            <form action="" method="POST" class="checkout-form flex" id="checkout-form">
                <div class="flex column">
                    <div class="payment-title">Método de pagamento</div>
                    <div class="flex">
                        <input type="radio" name="payment-method" id="cash" value="Dinheiro" checked>
                        <label for="cash">Dinheiro</label>
                    </div>

                    <div class="flex">
                        <input type="radio" name="payment-method" id="pix" value="Pix">
                        <label for="pix">Pix</label>
                    </div>

                    <div class="flex">
                        <input type="radio" name="payment-method" id="debit-card" value="Débito">
                        <label for="debit-card">Débito</label>
                    </div>

                    <div class="flex">
                        <input type="radio" name="payment-method" id="credit-card" value="Crédito">
                        <label for="credit-card">Crédito</label>
                    </div>
                </div>

                <div class="flex column">
                    <div class="payment-title">Inserir cliente</div>
                    <input type="text" name="costumer" id="costumer">
                    <button type="submit" name="submit-checkout">Finalizar</button>
                </div>
                
            </form>
        </div>
    </div>

{% endblock %}